-- Metadata-only reconstruction. Do not execute view queries or change session settings.
WITH target AS (
    SELECT c.*, n.nspname,
        pg_catalog.format('%I.%I', n.nspname, c.relname) AS qualified
    FROM pg_catalog.pg_class c
    JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = $1 AND c.relname = $2
      AND pg_catalog.has_schema_privilege(n.oid, 'USAGE')
      AND (pg_catalog.has_table_privilege(c.oid, 'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')
           OR pg_catalog.has_any_column_privilege(c.oid, 'SELECT,INSERT,UPDATE,REFERENCES'))
), definition AS (
    SELECT t.*,
        (SELECT pg_catalog.string_agg(pg_catalog.format('%I', a.attname), ', ' ORDER BY a.attnum)
         FROM pg_catalog.pg_attribute a WHERE a.attrelid = t.oid AND a.attnum > 0 AND NOT a.attisdropped) AS names,
        (SELECT pg_catalog.string_agg(
            '    ' || pg_catalog.format('%I %s', a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod))
            || CASE WHEN a.attcollation <> ty.typcollation THEN pg_catalog.format(' COLLATE %I.%I', cn.nspname, co.collname) ELSE '' END
            || CASE a.attidentity
                WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
                ELSE '' END
            || CASE WHEN a.attidentity <> '' THEN pg_catalog.format(
                ' (INCREMENT BY %s MINVALUE %s MAXVALUE %s START WITH %s CACHE %s %s)',
                seq.seqincrement, seq.seqmin, seq.seqmax, seq.seqstart, seq.seqcache,
                CASE WHEN seq.seqcycle THEN 'CYCLE' ELSE 'NO CYCLE' END) ELSE '' END
            || CASE a.attgenerated
                WHEN 's' THEN ' GENERATED ALWAYS AS (' || pg_catalog.pg_get_expr(d.adbin, d.adrelid) || ') STORED'
                WHEN 'v' THEN ' GENERATED ALWAYS AS (' || pg_catalog.pg_get_expr(d.adbin, d.adrelid) || ') VIRTUAL'
                ELSE CASE WHEN d.oid IS NOT NULL AND a.attidentity = '' THEN ' DEFAULT ' || pg_catalog.pg_get_expr(d.adbin, d.adrelid) ELSE '' END END
            || CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
            E',\n' ORDER BY a.attnum)
         FROM pg_catalog.pg_attribute a
         JOIN pg_catalog.pg_type ty ON ty.oid = a.atttypid
         LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
         LEFT JOIN pg_catalog.pg_collation co ON co.oid = a.attcollation
         LEFT JOIN pg_catalog.pg_namespace cn ON cn.oid = co.collnamespace
         LEFT JOIN LATERAL (
             SELECT s.* FROM pg_catalog.pg_sequence s JOIN pg_catalog.pg_depend dep ON dep.objid = s.seqrelid
             WHERE dep.classid = 'pg_catalog.pg_class'::regclass AND dep.refclassid = 'pg_catalog.pg_class'::regclass
               AND dep.refobjid = a.attrelid AND dep.refobjsubid = a.attnum AND dep.deptype = 'i'
         ) seq ON a.attidentity <> ''
         WHERE a.attrelid = t.oid AND a.attnum > 0 AND NOT a.attisdropped) AS columns,
        (SELECT pg_catalog.string_agg(pg_catalog.format('    CONSTRAINT %I %s', c.conname, pg_catalog.pg_get_constraintdef(c.oid)), E',\n' ORDER BY c.conname)
         FROM pg_catalog.pg_constraint c WHERE c.conrelid = t.oid AND c.contype IN ('p','u','f','c','x')) AS constraints
    FROM target t
)
SELECT pg_catalog.left(
    E'-- Structural DDL, not a backup. Referenced types/functions/sequences must exist.\n-- Owners, grants, policies, storage options, indexes, triggers and sequence state are not included.\n'
    || CASE
        WHEN relkind IN ('v','m') THEN
            pg_catalog.format('CREATE %sVIEW %s (%s)', CASE WHEN relkind = 'm' THEN 'MATERIALIZED ' ELSE '' END, qualified, names)
            || CASE WHEN relkind = 'v' AND reloptions IS NOT NULL THEN ' WITH (' || pg_catalog.array_to_string(reloptions, ', ') || ')' ELSE '' END
            || E' AS\n' || pg_catalog.rtrim(pg_catalog.pg_get_viewdef(oid), E';\n ')
            || CASE WHEN relkind = 'm' THEN E'\nWITH NO DATA;\n-- Refresh explicitly before browsing a newly created materialized view.' ELSE ';' END
        WHEN relkind = 'r' AND NOT relispartition AND NOT EXISTS (SELECT 1 FROM pg_catalog.pg_inherits i WHERE i.inhrelid = definition.oid) THEN
            pg_catalog.format('CREATE %sTABLE %s (', CASE relpersistence WHEN 'u' THEN 'UNLOGGED ' WHEN 't' THEN 'TEMPORARY ' ELSE '' END, qualified)
            || E'\n' || COALESCE(columns, '') || CASE WHEN constraints IS NOT NULL THEN CASE WHEN columns IS NOT NULL THEN E',\n' ELSE '' END || constraints ELSE '' END || E'\n);'
            || CASE WHEN relrowsecurity THEN E'\n' || pg_catalog.format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY;', qualified) ELSE '' END
            || CASE WHEN relforcerowsecurity THEN E'\n' || pg_catalog.format('ALTER TABLE %s FORCE ROW LEVEL SECURITY;', qualified) ELSE '' END
        ELSE '-- DDL reconstruction is unavailable for partitioned, inherited or foreign tables. Use PostgreSQL dump tools for their complete definition.'
    END, 2097153)
FROM definition;
