[package]
name = "klyndb-import"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
klyndb-driver-api = { path = "../driver-api" }
klyndb-query = { path = "../query" }
csv-core = "0.1"
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
tempfile.workspace = true
tokio.workspace = true
tokio-util.workspace = true
