#!/usr/bin/env python3
"""Collect exact locked dependency licenses and texts; no source from references."""
import json
import subprocess
from pathlib import Path

root = Path(__file__).resolve().parents[1]
entries = []
texts = []

def notice_files(directory):
    prefixes = ("license", "licence", "copying", "copyright", "notice", "unlicense", "ofl")
    return sorted(p for p in directory.iterdir() if p.is_file() and p.name.lower().startswith(prefixes)) if directory.exists() else []

def collect(ecosystem, name, version, license_expression, directory):
    if not license_expression:
        raise SystemExit(f"Missing license declaration: {ecosystem} {name}@{version}")
    entries.append((ecosystem, name, version, license_expression))
    header = f"{ecosystem}: {name}@{version} ({license_expression})"
    candidates = notice_files(directory)
    # Native libraries bundled by these crates have their own retained notices.
    bundled = {
        "libssh2-sys": ["libssh2/COPYING", "libssh2/LICENSES"],
        "openssl-src": ["openssl/LICENSE.txt"],
        "libz-sys": ["src/zlib/LICENSE", "src/zlib-ng/LICENSE.md"],
        "lz4-sys": ["liblz4/LICENSE", "liblz4/lib/LICENSE"],
    }
    for relative in bundled.get(name, []):
        path = directory / relative
        if path.is_dir():
            candidates.extend(sorted(p for p in path.iterdir() if p.is_file()))
        elif path.is_file():
            candidates.append(path)
    if name == "libduckdb-sys":
        if version != "1.10506.0":
            raise SystemExit("Update the pinned native DuckDB notices before changing libduckdb-sys")
        # The crate's generated native archive omits the original native notices.
        # Retain the corresponding pinned upstream texts in the repository.
        candidates.append(root / "third_party/duckdb-1.5.6/NOTICES.txt")
    for path in candidates:
        # Fail explicitly if a notice cannot be decoded; never silently drop it.
        texts.append(f"\n{'=' * 72}\n{header}\n{path.name}\n{'=' * 72}\n{path.read_text(encoding='utf-8')}\n")
    if not candidates:
        texts.append(f"\n{header}\nLicense declaration: {license_expression}\nSource package: {ecosystem} registry, exact version {version}\n")


def main():
    metadata = json.loads(subprocess.check_output(["cargo", "metadata", "--locked", "--format-version", "1"], cwd=root))
    desktop = root / "apps/desktop"
    lock = json.loads((desktop / "package-lock.json").read_text())
    for package in metadata["packages"]:
        if package["source"] or Path(package["manifest_path"]).resolve().is_relative_to(root / "third_party"):
            collect("Cargo", package["name"], package["version"], package["license"], Path(package["manifest_path"]).parent)
    for location, package in lock["packages"].items():
        if not location:
            continue
        directory = desktop / location
        manifest = json.loads((directory / "package.json").read_text()) if directory.exists() else {"name":location.rsplit("node_modules/",1)[-1]}
        expression = manifest.get("license", package.get("license"))
        if isinstance(expression, dict):
            expression = expression["type"]
        collect("npm", manifest["name"], package["version"], expression, directory)

    notice = root / "apps/desktop/src-tauri/resources/THIRD_PARTY_LICENSES.txt"
    notice.parent.mkdir(parents=True, exist_ok=True)
    notice.write_text("Klyndb locked dependency licenses. Includes build/dev and cross-target dependencies.\n" + "".join(texts))
    inventory = root / "docs/DEPENDENCY_LICENSES.md"
    inventory.write_text("# Locked dependency license inventory\n\nGenerated by `python3 scripts/license_inventory.py` after `npm ci`.\nIncludes build/dev and cross-target dependencies, not just runtime.\nRun cargo deny check licenses and review npm obligations before releases.\n\n| Ecosystem | Package | Version | License expression |\n| --- | --- | --- | --- |\n" + "".join(f"| {eco} | {name} | {version} | {license_expression.replace('|', '/')} |\n" for eco, name, version, license_expression in sorted(entries)))
    print(f"Collected {len(entries)} locked packages; bundled notices {notice.stat().st_size} bytes")


if __name__ == "__main__":
    main()
