use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use tokio::sync::mpsc;
use tokio_util::sync::CancellationToken;

#[derive(Debug, thiserror::Error)]
#[error("{message}")]
pub struct Error {
    pub message: String,
}
impl Error {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}
pub type Result<T> = std::result::Result<T, Error>;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(tag = "kind", content = "value", rename_all = "snake_case")]
pub enum Cell {
    Null,
    Text(String),
    Number(String),
    Boolean(bool),
    Binary(String),
    Json(serde_json::Value),
}
impl Cell {
    pub fn byte_len(&self) -> usize {
        match self {
            Self::Null => 0,
            Self::Text(v) | Self::Number(v) | Self::Binary(v) => v.len(),
            Self::Boolean(_) => 1,
            Self::Json(v) => v.to_string().len(),
        }
    }
    pub fn text(&self) -> String {
        match self {
            Self::Null => String::new(),
            Self::Text(v) | Self::Number(v) | Self::Binary(v) => v.clone(),
            Self::Boolean(v) => v.to_string(),
            Self::Json(v) => v.to_string(),
        }
    }
}
pub type Row = Vec<Cell>;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Capabilities {
    pub transactions: bool,
    pub schemas: bool,
    pub explain: bool,
    pub edit_rows: bool,
    pub cancel: bool,
    pub tls: bool,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Table {
    pub schema: String,
    pub name: String,
    pub kind: String,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Column {
    pub name: String,
    pub data_type: String,
    pub nullable: bool,
    pub primary_key: bool,
    pub default: Option<String>,
    pub generated: bool,
}
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TableInfo {
    pub editable: bool,
    pub columns: Vec<Column>,
    pub ddl: Option<String>,
    pub indexes: Vec<serde_json::Value>,
    pub foreign_keys: Vec<serde_json::Value>,
}

/// Old values are compared as well as the primary key: a stale edit must affect no rows.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Change {
    Insert {
        values: std::collections::BTreeMap<String, Cell>,
    },
    Update {
        old: Row,
        values: std::collections::BTreeMap<String, Cell>,
    },
    Delete {
        old: Row,
    },
}
impl Change {
    pub fn values(&self) -> Option<&std::collections::BTreeMap<String, Cell>> {
        match self {
            Self::Insert { values } | Self::Update { values, .. } => Some(values),
            Self::Delete { .. } => None,
        }
    }
    pub fn old(&self) -> Option<&Row> {
        match self {
            Self::Update { old, .. } | Self::Delete { old } => Some(old),
            Self::Insert { .. } => None,
        }
    }
    pub fn validate(&self, columns: &[Column]) -> Result<()> {
        if let Some(values) = self.values() {
            if matches!(self, Self::Update { .. }) && values.is_empty() {
                return Err(Error::new("No changed values"));
            }
            for name in values.keys() {
                let column = columns
                    .iter()
                    .find(|c| &c.name == name)
                    .ok_or_else(|| Error::new("Column no longer exists. Refresh the table."))?;
                if column.generated {
                    return Err(Error::new(format!(
                        "{} is generated by the database",
                        column.name
                    )));
                }
            }
        }
        if let Some(old) = self.old() {
            if old.len() != columns.len() {
                return Err(Error::new("Table columns changed. Refresh before editing."));
            }
            if !columns.iter().any(|c| c.primary_key)
                || columns
                    .iter()
                    .zip(old)
                    .any(|(c, v)| c.primary_key && matches!(v, Cell::Null))
            {
                return Err(Error::new("Update/delete requires a non-NULL primary key"));
            }
        }
        Ok(())
    }
}
#[derive(Clone, Debug, Serialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum TransactionState {
    Idle,
    Active,
    Failed,
}
#[derive(Clone, Debug, Serialize)]
pub struct MutationResult {
    pub affected: u64,
    pub pending_transaction: bool,
}
pub fn validate_change_batch(changes: &[Change]) -> Result<()> {
    if changes.is_empty() || changes.len() > 1000 {
        return Err(Error::new("Apply 1–1000 changes per batch"));
    }
    let bytes = changes
        .iter()
        .map(|c| {
            c.old()
                .into_iter()
                .flatten()
                .chain(c.values().into_iter().flat_map(|v| v.values()))
                .map(Cell::byte_len)
                .sum::<usize>()
                + c.values()
                    .map_or(0, |values| values.keys().map(String::len).sum::<usize>())
        })
        .sum::<usize>();
    if bytes > 8 * 1024 * 1024 {
        return Err(Error::new("An editing batch is limited to 8 MiB"));
    }
    Ok(())
}

pub enum Batch {
    Columns(Vec<String>),
    Rows(Vec<Row>),
    Complete { affected: u64, truncated: bool },
}

#[async_trait]
pub trait Session: Send + Sync {
    fn capabilities(&self) -> Capabilities;
    fn quote_identifier(&self, name: &str) -> String {
        quote_identifier(name)
    }
    fn table_select_sql(&self, table: &Table, limit: usize) -> Result<String> {
        if !(1..=10_000_000).contains(&limit) {
            return Err(Error::new("Row limit must be 1–10,000,000"));
        }
        Ok(format!(
            "SELECT * FROM {}.{} LIMIT {limit};",
            self.quote_identifier(&table.schema),
            self.quote_identifier(&table.name)
        ))
    }
    async fn execute(
        &self,
        sql: String,
        output: mpsc::Sender<Batch>,
        cancel: CancellationToken,
        limit: usize,
    ) -> Result<()>;
    async fn tables(&self) -> Result<Vec<Table>>;
    async fn inspect(&self, table: &Table) -> Result<TableInfo>;
    async fn transaction_state(&self) -> Result<TransactionState>;
    async fn apply_changes(&self, table: Table, changes: Vec<Change>) -> Result<MutationResult>;
    async fn disconnect(&self) -> Result<()>;
}

pub fn quote_identifier(name: &str) -> String {
    format!("\"{}\"", name.replace('"', "\"\""))
}
